apiVersion: v1
kind: Service
metadata:
  name: {{ include "vahter-chart.fullname" . }}
  labels:
    {{- include "vahter-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "vahter-chart.selectorLabels" . | nindent 4 }}